# This is a basic workflow to help you get started with Actions

name: NewRepoWorkflow

# Controls when the workflow will run
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the "main" branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom logic after Databricks push
        run: |
          echo "Changes pushed from Databricks."
          # Add testing, linting, sync, or deployment steps here
